import time
from playsound import playsound
from threading import Thread
import os
os.system('cls')
def play():
    playsound("PH.wav")
def lyric1():
    print("Playing : Penjaga Hati by nadhif basalamah")
    time.sleep(3)
    print("Karena", end=' ',flush=True) 
    time.sleep(1)
    print("bersamamu", end=' ',flush=True)
    time.sleep(1)
    print("semua", end=' ',flush=True)
    time.sleep(1.5)
    print("terasa", end=' ',flush=True)
    time.sleep(1)
    print("indah", end=' ',flush=True)
    time.sleep(2)
    os.system('cls')
    print("Playing : Penjaga Hati by nadhif basalamah")
    print("gundah", end=' ',flush=True)
    time.sleep(0.9)
    print("gulana", end=' ',flush=True)
    time.sleep(1)
    print("hatiku", end=' ',flush=True)
    time.sleep(1)
    print("telah", end=' ',flush=True)
    time.sleep(0.8)
    print("hancur", end=' ',flush=True)
    time.sleep(0.7)
    print("sirna")
    time.sleep(1.5)
    os.system('cls')
    print("Playing : Penjaga Hati by nadhif basalamah")
    print("janjiku", end=' ',flush=True) 
    time.sleep(1)
    print("takkan", end=' ',flush=True) 
    time.sleep(0.9)
    print("kulepas", end=' ',flush=True) 
    time.sleep(1.2)
    print("wahai", end=' ',flush=True)
    time.sleep(0.7)
    print("kau", end=' ',flush=True)
    time.sleep(0.7)
    print("bidadariku", end=' ',flush=True)
    time.sleep(1.5)
    print("dari", end=' ',flush=True)
    time.sleep(1)
    print("surga", end=' ',flush=True)
    time.sleep(1)
    os.system('cls')
    print("Playing : Penjaga Hati by nadhif basalamah")
    print("tuk", end=' ',flush=True)
    time.sleep(1)
    print("selamanya", end=' ',flush=True)
    time.sleep(3.5)
    os.system('cls')
    time.sleep(1)
    print("Playing : Penjaga Hati by nadhif basalamah")
    time.sleep(0.3)
    print("tuk", end=' ',flush=True)
    time.sleep(2.2)
    print("selamanya", end=' ',flush=True)
t1 = Thread(target=play)
t1.start()
t2 = Thread(target=lyric1)
t2.start()